export const authConstant = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const scheduleConstant = {
  Schedule_Request: 'Schedule_Request',
  GET_SCHEDULE_SUCCESS: 'GET_SCHEDULE_SUCCESS',
  GET_SCHEDULE_FAIL: 'GET_SCHEDULE_FAIL',
  GET_VACCINATED_BY_YOU_SUCCESS: 'GET_VACCINATED_BY_YOU_SUCCESS',
  GET_VACCINATED_BY_YOU_FAIL: 'GET_VACCINATED_BY_YOU_FAIL',
};
